# Generated by Django 5.0 on 2023-12-21 21:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("a_posts", "0003_tag_post_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={},
        ),
    ]
