# Generated by Django 5.0 on 2023-12-21 22:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("a_posts", "0004_alter_post_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="tag",
            name="order",
            field=models.IntegerField(null=True),
        ),
    ]
