# Generated by Django 5.0 on 2023-12-22 00:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("a_posts", "0005_alter_tag_options_tag_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="icons/"),
        ),
    ]
